### ISSUE TITLE
Users can have a flight made for them

### ISSUE THREAD

**Issue by keivanmojmali** [keivanmojmali/ajax-project#17]
## 💰 Motivation

Users like to drink good beer! 😄

## 📐 Plan

Allow the user to have a flight option made for them

## ✅ Task List

- [x] design a flight option page
- [x] add view capabilities 
- [x] add a function that will grab a beer from each abv category and store it in a flight array
- [x] function to display that flight once its picked
- [x] style for function not beauty
- [ ]
