### ISSUE TITLE
Users will know exactly how to use the website

### ISSUE THREAD

**Issue by keivanmojmali** [keivanmojmali/ajax-project#2]
## 💰 Motivation

Users like to use intuitive design! 😄

## 📐 Plan

Create a intuitive and uniform html and css code that can be re-used throughout website. 

## 🖼️ Wireframe

https://www.figma.com/file/jmZmglNe6BIQhJ8WZeKdfh/Beer?node-id=0%3A1

## ✅ Task List

- [x] Plan HTML layout 
- [x] Plan Responsive features
- [x] Plan Placeholders for later issues
- [x] Code HTML according to plans from previous steps
- [x] Code CSS with minimal styling - further styling to be applied later 
- [x] Add proper data-view attributes
