### ISSUE TITLE
User want to know what the website is about 

### ISSUE THREAD

**Issue by keivanmojmali** [keivanmojmali/ajax-project#20]
## 💰 Motivation

Users like to understand what the website is for! 😄

## 📐 Plan

Change elements and CSSto show the user value

## ✅ Task List

- [x] update carousel to show information about what the website does
- [x] add other styling as necessary 
- [x] update words on website to actual words
- [x] update website name
- [ ] 
- [x]  fix any bugs
