### ISSUE TITLE
New users can create profiles

### ISSUE THREAD

**Issue by keivanmojmali** [keivanmojmali/ajax-project#3]
## 💰 Motivation

Users like to be a part of the community! 😄

## 📐 Plan

Create a welcoming page that will lead people into clicking on sign up and then filling out our sign up form on the next page

## ✅ Task List

- [x] code HTML section to hidden for welcome page
- [x] add data model to data.js
- [x] add localStorage capability
- [x] design section to show a welcome page with filler text and buttons
- [x] code HTML section to hidden for sign up page
- [x] design a form that takes basic information
