### ISSUE TITLE
Users can explore beers

### ISSUE THREAD

**Issue by keivanmojmali** [keivanmojmali/ajax-project#4]
## 💰 Motivation

Users like to explore! 😄

## 📐 Plan

Design a page that showcases an Instagram style explorer page for beers

## ✅ Task List

- [x] code HTML section for explorer page 
- [x] HTML should include a fill list of details and an image 
- [x] all information besides image should be display:none 
- [x] container should be flex and wrap 
- [x] add top bar with absolute positioning styled according to wireframe
- [x] add navigation bar with absolute positioning styled according to wire frame 
- [x] add ability to "star" a beer that will save it to their favorites
- [x] add data rendering function
- [x] add Ajax ability to load random beers 
- [x] add load more option
- [ ]
