### ISSUE TITLE
User can see their profile and favorite beers

### ISSUE THREAD

**Issue by keivanmojmali** [keivanmojmali/ajax-project#5]
## 💰 Motivation

Users like to play favorites! 😄

## 📐 Plan

Create a profile page that will showcase their "starred" beers

## ✅ Task List

- [x] create a top div set to hidden that will show profile information - with filler information 
- [x] create a div list to hidden that will showcase all of the beers that a user has set to favorite
- [x] add css styling of ability to expand for favorites beer 
- [ ]
