### ISSUE TITLE
Users  like having functionality 

### ISSUE THREAD

**Issue by keivanmojmali** [keivanmojmali/ajax-project#7]
## 💰 Motivation

Users like having a website that works! 😄

## 📐 Plan

Add data model and JavaScript functionality 

## ✅ Task List

- [x] add a data model in data.js
- [x] add ability for data to be stored in localStorage
- [x] add ability for website to recognize if there is a profile or not
- [x] if there is not profile set - start user in join now page
- [x] add ability for form to be stored to data model 
- [x] add functionality of sign up button to store data and also take to explorer view
- [x] add functionality of buttons on bottom nav bar to change views 
- [x] add funtionality to bottom nav bar
- [x] add JS that will expand the clicked beer on explorer page and show other information about it
- [x] add ability to minimize expanded view
- [x] add ability for user to edit profile information
- [x] add ability for user to store beers on favorites list 
- [x] add fucntionality to lets do it button on plan my meal page
- [x] add randomizer meal planner for tonights beer paired with tonights food list
