### ISSUE TITLE
Users can add notes about their favorite beers under the comment section 

### ISSUE THREAD

**Issue by keivanmojmali** [keivanmojmali/ajax-project#8]
## 💰 Motivation

Users like to quickly find what they need! 😄

## 📐 Plan

Crate a well functioning top bar

## ✅ Task List

- [x] add ability to target div in favorites 
- [x] add button to div that initiates adding a comment
- [x] add a div that pops in with ability to write 
- [x] that note is now displayed and will stay there 
- [x] add ability to edit the note
