### ISSUE TITLE
Users like to see beauty

### ISSUE THREAD

**Issue by keivanmojmali** [keivanmojmali/ajax-project#9]
## 💰 Motivation

Users like to see good design! 😄

## 📐 Plan

Change stylings to make the page more attractive 

## ✅ Task List

- [x] add fonts for headers and paragraphs
- [x] add color schemes for different pages and the website as a whole
- [x] add button styling  
- [x] when users start on explorer page the beers are loaded
- [x] when users star their favorite beer it changes the star to filled in and vice versa and saves that data
- [x] increase the speed by fixing the network call issue and adding modals that can load more and make them wait while it loads
- [x] optimize the code by removing and joining things that can be joined 
- [x] fix loading issue when the user is a returning user
- [x] change to page function on punk api that returns 25 instead of looping 25 times  - you can also add a function at the bottom of the explorer that will load 25 more - you will need a loading now function to make sure the ajax is working
- [x] fix more or less info on favorites page - fix the star problem on favorites page
- [ ]
